version: "3"

volumes:
    kanban-data:

networks:
    frontend:
        name: kanban_frontend
    backend:
        name: kanban_backend

services:
    kanban-postgres:
        image: "postgres:9.6-alpine"
        container_name: kanban-postgres
        volumes:
            - kanban-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=kanban
            - POSTGRES_USER=kanban
            - POSTGRES_PASSWORD=kanban
        networks:
            - backend

    kanban-app:
        build: ./kanban-app
        container_name: kanban-app
        environment:
            - DB_SERVER=kanban-postgres # Keep this
            - POSTGRES_DB=kanban # Put this in an .env file
            - POSTGRES_USER=kanban # Put this in an .env file
            - POSTGRES_PASSWORD=kanban # Put this in an .env file
        ports:
            - 8080:8080
        links:
            - kanban-postgres
        networks:
            - backend
            - frontend

    kanban-ui:
        build: ./kanban-ui
        container_name: kanban-ui
        ports:
            - 4200:80
        links:
            - kanban-app
        networks:
            - frontend
