version: "3"

networks:
    db:
    backend:
    ui:

volumes:
    mysql-volume:
        name: mysql

services:
    mysql:
        image: mysql:8
        restart: always
        volumes:
            - mysql-volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=sde_test_db
        networks:
            - db

    api:
        build: ./api
        volumes:
            - ./api/src:/usr/app/src
        env_file:
            - api-mysql.env
        depends_on:
            - mysql
        networks:
            - backend
            - db

    web:
        image: nginx:1-alpine
        volumes:
            - ./web:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 3000:3000
        depends_on:
            - api
        networks:
            - backend
            - ui
