version: "3"

services:
    mysql:
        image: mysql:8
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=sde_test_db

    phpmyadmin:
        image: phpmyadmin:5
        restart: always
        env_file:
            - phpmyadmin.env
        depends_on:
            - mysql
        ports:
            - 8000:80
